export const DATA_LOAD_START = 'data_load_start'
export const DATA_LOAD_SUCCESS = 'data_load_success'
export const DATA_LOAD_ERROR = 'data_load_error'
export const DATA_CLEAR = 'data_clear'
export const DATA_FILTER = 'data_filter'